# Generated by Django 4.2.4 on 2023-08-31 10:01

import ckeditor.fields
from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('main_image', models.ImageField(help_text='720x584', upload_to=services.uploader.Uploader.upload_photo_for_service, verbose_name='Esas sekil')),
                ('head_1', models.CharField(max_length=255, verbose_name='Basliq 1')),
                ('desc_1', ckeditor.fields.RichTextField()),
                ('head_2', models.CharField(max_length=255, verbose_name='Basliq 2')),
                ('desc_2', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Xidmet',
                'verbose_name_plural': 'Xidmetler',
                'ordering': ('-created_at',),
            },
        ),
    ]
