# Generated by Django 4.2.4 on 2023-08-31 10:04

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('images', models.ImageField(upload_to=services.uploader.Uploader.upload_photo_for_service)),
            ],
            options={
                'verbose_name': 'Xidmet sekili',
                'verbose_name_plural': 'Xidmetlerin sekilleri',
                'ordering': ('-created_at',),
            },
        ),
    ]
