# Generated by Django 4.2.4 on 2023-08-31 10:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0003_serviceimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_1_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_1_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_2_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='desc_2_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='head_1_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Basliq 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='head_1_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Basliq 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='head_2_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Basliq 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='head_2_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Basliq 2'),
        ),
        migrations.AddField(
            model_name='serviceimages',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teserrufat.service'),
        ),
    ]
