# Generated by Django 4.2.4 on 2023-08-31 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0004_category_name_az_category_name_ru_service_desc_1_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teserrufat.category'),
        ),
    ]
