# Generated by Django 4.2.4 on 2023-08-31 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0005_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQualities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Keyfiyyətlər')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teserrufat.service')),
            ],
            options={
                'verbose_name': 'Keyfiyyət',
                'verbose_name_plural': 'Keyfiyyətlər',
                'ordering': ('-created_at',),
            },
        ),
    ]
