# Generated by Django 4.2.4 on 2023-08-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0006_servicequalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicequalities',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Keyfiyyətlər'),
        ),
        migrations.AddField(
            model_name='servicequalities',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Keyfiyyətlər'),
        ),
    ]
