# Generated by Django 4.2.4 on 2023-08-31 11:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0007_servicequalities_name_az_servicequalities_name_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('question', models.CharField(max_length=255, verbose_name='Sual')),
                ('question_az', models.CharField(max_length=255, null=True, verbose_name='Sual')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Sual')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Cavab')),
                ('answer_az', ckeditor.fields.RichTextField(null=True, verbose_name='Cavab')),
                ('answer_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Cavab')),
            ],
            options={
                'verbose_name': 'Tez-tez verilən sual',
                'verbose_name_plural': 'Tez-tez verilən suallar',
                'ordering': ('-created_at',),
            },
        ),
    ]
