# Generated by Django 4.2.4 on 2023-08-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0008_frequentlyaskedquestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-created_at',), 'verbose_name': 'Xidmət', 'verbose_name_plural': 'Xidmətlər'},
        ),
        migrations.AlterModelOptions(
            name='serviceimages',
            options={'ordering': ('-created_at',), 'verbose_name': 'Xidmət sekili', 'verbose_name_plural': 'Xidmətlərin şəkilləri'},
        ),
    ]
