# Generated by Django 4.2.4 on 2023-08-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0009_alter_service_options_alter_serviceimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimages',
            options={'ordering': ('-created_at',), 'verbose_name': 'Xidmət şəkili', 'verbose_name_plural': 'Xidmətlərin şəkilləri'},
        ),
    ]
