# Generated by Django 4.2.4 on 2023-08-31 11:40

import ckeditor.fields
from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0010_alter_serviceimages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('main_image', models.ImageField(help_text='500x645', upload_to=services.uploader.Uploader.upload_photo_for_about, verbose_name='Əsas şəkil')),
                ('head', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıqlama')),
                ('left_image', models.ImageField(help_text='300x400', upload_to=services.uploader.Uploader.upload_photo_for_about, verbose_name='Sol şəkil')),
                ('right_top_image', models.ImageField(help_text='300x280', upload_to=services.uploader.Uploader.upload_photo_for_about, verbose_name='Yuxarı sağ şəkil')),
                ('right_bottom_image', models.ImageField(help_text='300x280', upload_to=services.uploader.Uploader.upload_photo_for_about, verbose_name='Aşağı sağ şəkil')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
                'ordering': ('-created_at',),
            },
        ),
    ]
