# Generated by Django 4.2.4 on 2023-08-31 11:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0011_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='head_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='head_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Başlıq'),
        ),
    ]
