# Generated by Django 4.2.4 on 2023-08-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0012_aboutmodel_description_az_aboutmodel_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad və soyad')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Əlaqə nömrəsi')),
                ('email', models.EmailField(max_length=255, verbose_name='E-poçt ünvanı')),
                ('message', models.TextField(verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'Əlaqə saxlamaq istəyən şəxs',
                'verbose_name_plural': 'Əlaqə saxlamaq istəyən şəxslər',
                'ordering': ('-created_at',),
            },
        ),
    ]
