# Generated by Django 4.2.4 on 2023-09-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0013_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('iframe_link', models.TextField(verbose_name='Video linki')),
            ],
            options={
                'verbose_name': 'Bizim iş',
                'verbose_name_plural': 'Bizim işlərimiz',
                'ordering': ('-created_at',),
            },
        ),
    ]
