# Generated by Django 4.2.4 on 2023-09-01 07:52

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0014_ourworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('video', models.FileField(upload_to=services.uploader.Uploader.upload_video_for_index, verbose_name='Ana səhifə video')),
            ],
            options={
                'verbose_name': 'Ana səhifə video',
                'verbose_name_plural': 'Ana səhifə video',
                'ordering': ('-created_at',),
            },
        ),
    ]
