# Generated by Django 4.2.4 on 2023-09-01 08:10

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0015_indexvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='indexvideo',
            name='video_cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_video_for_index, verbose_name='Video örtük şəkili'),
        ),
        migrations.AddField(
            model_name='indexvideo',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Video linki'),
        ),
    ]
