# Generated by Django 4.2.4 on 2023-09-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0016_remove_indexvideo_video_indexvideo_video_cover_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexvideo',
            name='word',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Video üzərindəki yazı'),
        ),
    ]
