# Generated by Django 4.2.4 on 2023-09-01 11:35

import ckeditor.fields
from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0017_indexvideo_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('header_logo', models.ImageField(upload_to=services.uploader.Uploader.upload_logo_for_index, verbose_name='Ana səhifə yuxarı loqo')),
                ('footer_logo', models.ImageField(upload_to=services.uploader.Uploader.upload_logo_for_index, verbose_name='Ana səhifə aşağı loqo')),
                ('footer_text', ckeditor.fields.RichTextField(verbose_name='Ana səhifə aşağı mətn')),
            ],
            options={
                'verbose_name': 'Ana səhifə başlıq və aşağı düzəliş',
                'verbose_name_plural': 'Ana səhifə başlıq və aşağı düzəlişlər',
                'ordering': ('-created_at',),
            },
        ),
    ]
