# Generated by Django 4.2.4 on 2023-09-01 11:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0018_indexconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexconfig',
            name='footer_text_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ana səhifə aşağı mətn'),
        ),
        migrations.AddField(
            model_name='indexconfig',
            name='footer_text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ana səhifə aşağı mətn'),
        ),
        migrations.AddField(
            model_name='indexvideo',
            name='word_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Video üzərindəki yazı'),
        ),
        migrations.AddField(
            model_name='indexvideo',
            name='word_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Video üzərindəki yazı'),
        ),
    ]
