# Generated by Django 4.2.4 on 2023-09-01 12:11

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0019_indexconfig_footer_text_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('images', models.ImageField(upload_to=services.uploader.Uploader.upload_slider_image_for_index, verbose_name='Ana səhifə slider şəkilləri')),
                ('head_1', models.CharField(max_length=255, verbose_name='Şəkilin üzərindəki rəngli yazı')),
                ('head_1_az', models.CharField(max_length=255, null=True, verbose_name='Şəkilin üzərindəki rəngli yazı')),
                ('head_1_ru', models.CharField(max_length=255, null=True, verbose_name='Şəkilin üzərindəki rəngli yazı')),
                ('main_sentence', models.CharField(max_length=255, verbose_name='Əsas böyük yazı')),
                ('main_sentence_az', models.CharField(max_length=255, null=True, verbose_name='Əsas böyük yazı')),
                ('main_sentence_ru', models.CharField(max_length=255, null=True, verbose_name='Əsas böyük yazı')),
                ('little_sentence', models.CharField(max_length=255, verbose_name='Şrifti kiçik olan yazı')),
                ('little_sentence_az', models.CharField(max_length=255, null=True, verbose_name='Şrifti kiçik olan yazı')),
                ('little_sentence_ru', models.CharField(max_length=255, null=True, verbose_name='Şrifti kiçik olan yazı')),
            ],
            options={
                'verbose_name': 'Ana səhifə slider parametr',
                'verbose_name_plural': 'Ana səhifə slider parametrləri',
                'ordering': ('-created_at',),
            },
        ),
    ]
