# Generated by Django 4.2.4 on 2023-09-02 13:54

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0020_indexslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('main_sentence', models.CharField(max_length=255, verbose_name='Əsas cümlə')),
                ('image', models.ImageField(help_text='370x537', upload_to=services.uploader.Uploader.upload_image_for_sidebar, verbose_name='Şəkil')),
            ],
            options={
                'verbose_name': 'Detal səhifəsi yan hissə',
                'verbose_name_plural': 'Detal səhifəsi yan hissə',
                'ordering': ('-created_at',),
            },
        ),
    ]
