# Generated by Django 4.2.4 on 2023-09-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0021_detailsidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsidebar',
            name='main_sentence_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Əsas cümlə'),
        ),
        migrations.AddField(
            model_name='detailsidebar',
            name='main_sentence_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Əsas cümlə'),
        ),
    ]
