# Generated by Django 4.2.4 on 2023-09-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0022_detailsidebar_main_sentence_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsidebar',
            name='main_sentence',
        ),
        migrations.RemoveField(
            model_name='detailsidebar',
            name='main_sentence_az',
        ),
        migrations.RemoveField(
            model_name='detailsidebar',
            name='main_sentence_ru',
        ),
    ]
