# Generated by Django 4.2.4 on 2023-09-02 14:10

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0023_remove_detailsidebar_main_sentence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(help_text='456x516', upload_to=services.uploader.Uploader.upload_image_for_sidebar)),
            ],
            options={
                'verbose_name': 'Əlaqə formunun yanındakı şəkil',
                'verbose_name_plural': 'Əlaqə formunun yanındakı şəkil',
                'ordering': ('-created_at',),
            },
        ),
    ]
