# Generated by Django 4.2.4 on 2023-09-02 14:20

import ckeditor.fields
from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0024_contactimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_image_for_favicon, verbose_name='Favikon'),
        ),
        migrations.AlterField(
            model_name='indexconfig',
            name='footer_logo',
            field=models.ImageField(upload_to=services.uploader.Uploader.upload_logo_for_index, verbose_name='Aşağı loqo'),
        ),
        migrations.AlterField(
            model_name='indexconfig',
            name='footer_text',
            field=ckeditor.fields.RichTextField(verbose_name='Footer mətn'),
        ),
        migrations.AlterField(
            model_name='indexconfig',
            name='footer_text_az',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Footer mətn'),
        ),
        migrations.AlterField(
            model_name='indexconfig',
            name='footer_text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Footer mətn'),
        ),
        migrations.AlterField(
            model_name='indexconfig',
            name='header_logo',
            field=models.ImageField(upload_to=services.uploader.Uploader.upload_logo_for_index, verbose_name='Yuxarı loqo'),
        ),
    ]
