# Generated by Django 4.2.4 on 2023-09-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0025_indexconfig_favicon_alter_indexconfig_footer_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('phones', models.CharField(max_length=255, verbose_name='Əlaqə nömrəsi')),
                ('is_main', models.BooleanField(default=False)),
                ('main_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teserrufat.indexconfig')),
            ],
            options={
                'verbose_name': 'Əlaqə nömrəsi',
                'verbose_name_plural': 'Əlaqə nömrələri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('emails', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_main', models.BooleanField(default=False)),
                ('main_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teserrufat.indexconfig')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emaillər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('address', models.TextField(verbose_name='Ünvan')),
                ('is_main', models.BooleanField(default=False)),
                ('main_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teserrufat.indexconfig')),
            ],
            options={
                'verbose_name': 'Ünvan',
                'verbose_name_plural': 'Ünvanlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
