# Generated by Django 4.2.4 on 2023-09-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0026_phones_emails_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_az',
            field=models.TextField(null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Ünvan'),
        ),
    ]
