# Generated by Django 4.2.4 on 2023-09-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0027_address_address_az_address_address_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('social_type', models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('tiktok', 'Tiktok'), ('yt', 'YouTube')], max_length=255, verbose_name='Sosial media')),
                ('social_link', models.TextField(verbose_name='Sosial media linki')),
            ],
            options={
                'verbose_name': 'Sosial media',
                'verbose_name_plural': 'Sosial media hesabları',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TitleDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('page_type', models.CharField(choices=[('home', 'Home Page'), ('about', 'About page'), ('contact', 'Contact'), ('services', 'Services'), ('our_works', 'Our Works')], max_length=255, verbose_name='Səhifənin tipi')),
                ('page_title', models.CharField(max_length=255, verbose_name='Səhifənın başlığı')),
                ('page_title_az', models.CharField(max_length=255, null=True, verbose_name='Səhifənın başlığı')),
                ('page_title_ru', models.CharField(max_length=255, null=True, verbose_name='Səhifənın başlığı')),
                ('page_description', models.TextField(verbose_name='Səhifənin açıqlaması')),
                ('page_description_az', models.TextField(null=True, verbose_name='Səhifənin açıqlaması')),
                ('page_description_ru', models.TextField(null=True, verbose_name='Səhifənin açıqlaması')),
            ],
            options={
                'verbose_name': 'Başlıq',
                'verbose_name_plural': 'Başlıqlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
