# Generated by Django 4.2.4 on 2023-09-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0028_socialmedia_titledescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='E-poçt ünvanı')),
            ],
            options={
                'verbose_name': 'Abunə',
                'verbose_name_plural': 'Abunələr',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='indexconfig',
            options={'ordering': ('-created_at',), 'verbose_name': 'Əsas məlumat', 'verbose_name_plural': 'Əsas məlumatlar'},
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_type',
            field=models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('tiktok', 'Tiktok'), ('yt', 'YouTube'), ('telegram', 'Telegram')], max_length=255, verbose_name='Sosial media'),
        ),
    ]
