# Generated by Django 4.2.4 on 2023-09-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0029_subscribe_alter_indexconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsidebar',
            name='image',
        ),
        migrations.AddField(
            model_name='detailsidebar',
            name='bottom_sentence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aşağıdakı cümlə'),
        ),
        migrations.AddField(
            model_name='detailsidebar',
            name='top_sentence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yuxarıdakı cümlə'),
        ),
    ]
