# Generated by Django 4.2.4 on 2023-09-02 20:37

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0030_remove_detailsidebar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titledescription',
            name='page_slide_image',
            field=models.ImageField(blank=True, help_text='2038x549', null=True, upload_to=services.uploader.Uploader.upload_image_for_pages_slider, verbose_name='Səhifə yuxarı hissə şəkil'),
        ),
    ]
