# Generated by Django 4.2.4 on 2023-09-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0031_titledescription_page_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titledescription',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About page'), ('contact', 'Contact'), ('services', 'Services'), ('our_works', 'Our Works'), ('service_detail', 'Service detail')], max_length=255, verbose_name='Səhifənin tipi'),
        ),
    ]
