# Generated by Django 4.2.5 on 2023-09-26 13:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0032_alter_titledescription_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='desc_1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc_1_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc_1_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc_2_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc_2_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='head_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Basliq 1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='head_1_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Basliq 1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='head_1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Basliq 1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='head_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Basliq 2'),
        ),
        migrations.AlterField(
            model_name='service',
            name='head_2_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Basliq 2'),
        ),
        migrations.AlterField(
            model_name='service',
            name='head_2_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Basliq 2'),
        ),
    ]
