# Generated by Django 4.2.5 on 2023-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0033_alter_service_desc_1_alter_service_desc_1_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Sehifenin descriptionu'),
        ),
        migrations.AddField(
            model_name='service',
            name='page_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sehifenin title i'),
        ),
    ]
