# Generated by Django 5.2.14 on 2026-05-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0035_indexconfig_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='page_description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Sehifenin descriptionu'),
        ),
        migrations.AddField(
            model_name='service',
            name='page_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Sehifenin descriptionu'),
        ),
        migrations.AddField(
            model_name='service',
            name='page_title_az',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sehifenin title i'),
        ),
        migrations.AddField(
            model_name='service',
            name='page_title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sehifenin title i'),
        ),
    ]
