# Generated by Django 4.2.13 on 2026-06-08 18:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('teserrufat', '0036_service_page_description_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(upload_to=services.uploader.Uploader.upload_logo_for_partner, verbose_name='Loqo')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Partnyor',
                'verbose_name_plural': 'Partnyorlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('main_image', models.ImageField(upload_to=services.uploader.Uploader.upload_photo_for_product, verbose_name='Əsas şəkil')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('title_az', models.CharField(max_length=255, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Başlıq')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt başlıq')),
                ('subtitle_az', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt başlıq')),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt başlıq')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Qısa açıqlama')),
                ('short_description_az', models.TextField(blank=True, null=True, verbose_name='Qısa açıqlama')),
                ('short_description_ru', models.TextField(blank=True, null=True, verbose_name='Qısa açıqlama')),
                ('head_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq 1')),
                ('head_1_az', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq 1')),
                ('head_1_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq 1')),
                ('desc_1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıqlama 1')),
                ('desc_1_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıqlama 1')),
                ('desc_1_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıqlama 1')),
                ('head_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq 2')),
                ('head_2_az', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq 2')),
                ('head_2_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlıq 2')),
                ('desc_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıqlama 2')),
                ('desc_2_az', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıqlama 2')),
                ('desc_2_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıqlama 2')),
                ('page_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sehifenin title i')),
                ('page_title_az', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sehifenin title i')),
                ('page_title_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sehifenin title i')),
                ('page_description', models.TextField(blank=True, null=True, verbose_name='Sehifenin descriptionu')),
                ('page_description_az', models.TextField(blank=True, null=True, verbose_name='Sehifenin descriptionu')),
                ('page_description_ru', models.TextField(blank=True, null=True, verbose_name='Sehifenin descriptionu')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_az', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Məhsul kateqoriyası',
                'verbose_name_plural': 'Məhsul kateqoriyaları',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Cədvəlin başlığı')),
                ('title_az', models.CharField(max_length=255, null=True, verbose_name='Cədvəlin başlığı')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Cədvəlin başlığı')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teserrufat.product')),
            ],
            options={
                'verbose_name': 'Məhsul cədvəli',
                'verbose_name_plural': 'Məhsul cədvəlləri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='titledescription',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About page'), ('contact', 'Contact'), ('services', 'Services'), ('our_works', 'Our Works'), ('service_detail', 'Service detail'), ('products', 'Products'), ('product_detail', 'Product detail')], max_length=255, verbose_name='Səhifənin tipi'),
        ),
        migrations.CreateModel(
            name='ProductTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ad')),
                ('name_az', models.CharField(max_length=255, null=True, verbose_name='Ad')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Ad')),
                ('value', models.CharField(max_length=255, verbose_name='Dəyər')),
                ('value_az', models.CharField(max_length=255, null=True, verbose_name='Dəyər')),
                ('value_ru', models.CharField(max_length=255, null=True, verbose_name='Dəyər')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teserrufat.producttable')),
            ],
            options={
                'verbose_name': 'Cədvəl sətri',
                'verbose_name_plural': 'Cədvəl sətirləri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Sənədin adı')),
                ('name_az', models.CharField(max_length=255, null=True, verbose_name='Sənədin adı')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Sənədin adı')),
                ('file', models.FileField(upload_to=services.uploader.Uploader.upload_document_for_product, verbose_name='Sənəd')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teserrufat.product')),
            ],
            options={
                'verbose_name': 'Məhsul sənədi',
                'verbose_name_plural': 'Məhsul sənədləri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teserrufat.productcategory'),
        ),
    ]
